# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: algobowl/problemsupport/v1/problem_support.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import algobowl.problemsupport.v1.problem_support_pb2 as algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2


class ProblemSupportService(Protocol):
    async def get_problem_info(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def verify_input(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def verify_output(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def generate_input(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def solve(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProblemSupportServiceASGIApplication(ConnectASGIApplication[ProblemSupportService]):
    def __init__(self, service: ProblemSupportService | AsyncGenerator[ProblemSupportService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/algobowl.problemsupport.v1.ProblemSupportService/GetProblemInfo": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProblemInfo",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_problem_info,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/VerifyInput": Endpoint.unary(
                    method=MethodInfo(
                        name="VerifyInput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.verify_input,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/VerifyOutput": Endpoint.unary(
                    method=MethodInfo(
                        name="VerifyOutput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.verify_output,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/GenerateInput": Endpoint.unary(
                    method=MethodInfo(
                        name="GenerateInput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate_input,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/Solve": Endpoint.unary(
                    method=MethodInfo(
                        name="Solve",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.solve,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/algobowl.problemsupport.v1.ProblemSupportService"


class ProblemSupportServiceClient(ConnectClient):
    async def get_problem_info(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProblemInfo",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def verify_input(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyInput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def verify_output(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyOutput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def generate_input(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateInput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def solve(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Solve",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ProblemSupportServiceSync(Protocol):
    def get_problem_info(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def verify_input(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def verify_output(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def generate_input(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def solve(self, request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest, ctx: RequestContext) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProblemSupportServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProblemSupportServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/algobowl.problemsupport.v1.ProblemSupportService/GetProblemInfo": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProblemInfo",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_problem_info,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/VerifyInput": EndpointSync.unary(
                    method=MethodInfo(
                        name="VerifyInput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.verify_input,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/VerifyOutput": EndpointSync.unary(
                    method=MethodInfo(
                        name="VerifyOutput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.verify_output,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/GenerateInput": EndpointSync.unary(
                    method=MethodInfo(
                        name="GenerateInput",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate_input,
                ),
                "/algobowl.problemsupport.v1.ProblemSupportService/Solve": EndpointSync.unary(
                    method=MethodInfo(
                        name="Solve",
                        service_name="algobowl.problemsupport.v1.ProblemSupportService",
                        input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
                        output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.solve,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/algobowl.problemsupport.v1.ProblemSupportService"


class ProblemSupportServiceClientSync(ConnectClientSync):
    def get_problem_info(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProblemInfo",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GetProblemInfoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def verify_input(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyInput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def verify_output(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyOutput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.VerifyOutputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def generate_input(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateInput",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.GenerateInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def solve(
        self,
        request: algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Solve",
                service_name="algobowl.problemsupport.v1.ProblemSupportService",
                input=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveRequest,
                output=algobowl_dot_problemsupport_dot_v1_dot_problem__support__pb2.SolveResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
